In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
# Load the dataset
data_path = "../data/asthma_disease_data.csv"
df = pd.read_csv(data_path)

In [3]:
# import pandas as pd
# from sklearn.preprocessing import StandardScaler

# # Assuming 'df' is your original DataFrame
# # Save original column names
# column_names = df.columns

# label_encoder = LabelEncoder()
# df['DoctorInCharge'] = label_encoder.fit_transform(df['DoctorInCharge'])

# # Standardize numeric features
# scaler = StandardScaler()
# df = scaler.fit_transform(df)  # scaled_data is a NumPy array

# # Verify the shape of scaled_data
# print("Shape of scaled_data:", scaled_data.shape)

# # Ensure that column_names have the correct number of columns
# print("Number of column names:", len(column_names))

# # Create a DataFrame from the scaled data
# df = pd.DataFrame(df, columns=column_names)

# # Final inspection
# print(df.head())
# print(df.info())

In [4]:
df

,PatientID,Age,Gender,Ethnicity,EducationLevel,BMI,Smoking,PhysicalActivity,DietQuality,SleepQuality,...,LungFunctionFEV1,LungFunctionFVC,Wheezing,ShortnessOfBreath,ChestTightness,Coughing,NighttimeSymptoms,ExerciseInduced,Diagnosis,DoctorInCharge
0,5034,63,0,1,0,15.848744,0,0.894448,5.488696,8.701003,...,1.369051,4.941206,0,0,1,0,0,1,0,Dr_Confid
1,5035,26,1,2,2,22.757042,0,5.897329,6.341014,5.153966,...,2.197767,1.702393,1,0,0,1,1,1,0,Dr_Confid
2,5036,57,0,2,1,18.395396,0,6.739367,9.196237,6.840647,...,1.698011,5.022553,1,1,1,0,1,1,0,Dr_Confid
3,5037,40,1,2,1,38.515278,0,1.404503,5.826532,4.253036,...,3.032037,2.300159,1,0,1,1,1,0,0,Dr_Confid
4,5038,61,0,0,3,19.283802,0,4.604493,3.127048,9.625799,...,3.470589,3.067944,1,1,1,0,0,1,0,Dr_Confid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2387,7421,43,1,0,2,29.059613,0,3.019854,6.119637,8.300960,...,3.125249,5.166032,0,1,0,0,0,1,1,Dr_Confid
2388,7422,18,1,0,1,20.740850,0,5.805180,4.386992,7.731192,...,1.132977,5.509502,0,0,0,1,1,0,1,Dr_Confid
2389,7423,54,0,3,2,37.079560,0,4.735169,8.214064,7.483521,...,1.685962,3.346877,1,0,1,1,0,1,1,Dr_Confid
2390,7424,46,1,0,2,23.444712,0,9.672637,7.362861,6.717272,...,3.481549,1.713274,0,1,1,0,1,1,0,Dr_Confid
2391,7425,26,1,0,0,28.123021,1,1.613138,7.412878,8.512253,...,2.280613,2.453284,1,1,0,0,1,0,0,Dr_Confid

In [5]:
df.shape

(2392, 29)

In [6]:
df.dtypes

PatientID                   int64
Age                         int64
Gender                      int64
Ethnicity                   int64
EducationLevel              int64
BMI                       float64
Smoking                     int64
PhysicalActivity          float64
DietQuality               float64
SleepQuality              float64
PollutionExposure         float64
PollenExposure            float64
DustExposure              float64
PetAllergy                  int64
FamilyHistoryAsthma         int64
HistoryOfAllergies          int64
Eczema                      int64
HayFever                    int64
GastroesophagealReflux      int64
LungFunctionFEV1          float64
LungFunctionFVC           float64
Wheezing                    int64
ShortnessOfBreath           int64
ChestTightness              int64
Coughing                    int64
NighttimeSymptoms           int64
ExerciseInduced             int64
Diagnosis                   int64
DoctorInCharge             object
dtype: object

In [7]:
# Fill missing values (example: mean imputation)
df.fillna(df.mean(), inplace=True)

C:\Users\galin\AppData\Local\Temp\ipykernel_38076\2350445341.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.fillna(df.mean(), inplace=True)

In [8]:
label_encoder = LabelEncoder()
df['DoctorInCharge'] = label_encoder.fit_transform(df['DoctorInCharge'])

# Convert categorical variables using one-hot encoding
# df['DoctorInCharge'] = pd.get_dummies(df['DoctorInCharge'])

In [9]:
df['DoctorInCharge']

0       0
1       0
2       0
3       0
4       0
       ..
2387    0
2388    0
2389    0
2390    0
2391    0
Name: DoctorInCharge, Length: 2392, dtype: int32

In [10]:
# Create new features (e.g., interaction terms)
df['age_bmi_interaction'] = df['Age'] * df['BMI']

In [11]:
df['age_bmi_interaction']

0        998.470897
1        591.683094
2       1048.537599
3       1540.611116
4       1176.311925
           ...
2387    1249.563345
2388     373.335298
2389    2002.296236
2390    1078.456759
2391     731.198551
Name: age_bmi_interaction, Length: 2392, dtype: float64

In [12]:
column_names = df.columns
print("Number of column names:", len(column_names))

Number of column names: 30

In [13]:
# Standardize numeric features
scaler = StandardScaler()
df = scaler.fit_transform(df)

In [14]:
df.shape

(2392, 30)

In [18]:
df = pd.DataFrame(df, columns=column_names)

# Final inspection
df.head()

,PatientID,Age,Gender,Ethnicity,EducationLevel,BMI,Smoking,PhysicalActivity,DietQuality,SleepQuality,...,LungFunctionFVC,Wheezing,ShortnessOfBreath,ChestTightness,Coughing,NighttimeSymptoms,ExerciseInduced,Diagnosis,DoctorInCharge,age_bmi_interaction
0,-1.731327,0.965740,-0.986710,0.334986,-1.455673,-1.582769,-0.406355,-1.432099,0.160113,0.971063,...,0.920608,-1.214986,-1.000836,0.993333,-1.006711,-1.230954,0.808131,-0.233824,0.0,-0.221978
1,-1.729879,-0.747054,1.013469,1.349273,0.771363,-0.623300,-0.406355,0.291269,0.453069,-1.076746,...,-1.564256,0.823055,-1.000836,-1.006711,0.993333,0.812378,0.808131,-0.233824,0.0,-0.815692
2,-1.728430,0.687989,-0.986710,1.349273,-0.342155,-1.229074,-0.406355,0.581330,1.434458,-0.102976,...,0.983019,0.823055,0.999164,0.993333,-1.006711,0.812378,0.808131,-0.233824,0.0,-0.148905
3,-1.726982,-0.098970,1.013469,1.349273,-0.342155,1.565307,-0.406355,-1.256398,0.276233,-1.596880,...,-1.105641,0.823055,-1.000836,0.993333,0.993333,0.812378,-1.237424,-0.233824,0.0,0.569286
4,-1.725534,0.873156,-0.986710,-0.679301,1.884880,-1.105686,-0.406355,-0.154081,-0.651625,1.504976,...,-0.516586,0.823055,0.999164,0.993333,-1.006711,-1.230954,0.808131,-0.233824,0.0,0.037584

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2392 entries, 0 to 2391
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   PatientID               2392 non-null   float64
 1   Age                     2392 non-null   float64
 2   Gender                  2392 non-null   float64
 3   Ethnicity               2392 non-null   float64
 4   EducationLevel          2392 non-null   float64
 5   BMI                     2392 non-null   float64
 6   Smoking                 2392 non-null   float64
 7   PhysicalActivity        2392 non-null   float64
 8   DietQuality             2392 non-null   float64
 9   SleepQuality            2392 non-null   float64
 10  PollutionExposure       2392 non-null   float64
 11  PollenExposure          2392 non-null   float64
 12  DustExposure            2392 non-null   float64
 13  PetAllergy              2392 non-null   float64
 14  FamilyHistoryAsthma     2392 non-null   float64
 15  HistoryOfAllergies      2392 non-null   float64
 16  Eczema                  2392 non-null   float64
 17  HayFever                2392 non-null   float64
 18  GastroesophagealReflux  2392 non-null   float64
 19  LungFunctionFEV1        2392 non-null   float64
 20  LungFunctionFVC         2392 non-null   float64
 21  Wheezing                2392 non-null   float64
 22  ShortnessOfBreath       2392 non-null   float64
 23  ChestTightness          2392 non-null   float64
 24  Coughing                2392 non-null   float64
 25  NighttimeSymptoms       2392 non-null   float64
 26  ExerciseInduced         2392 non-null   float64
 27  Diagnosis               2392 non-null   float64
 28  DoctorInCharge          2392 non-null   float64
 29  age_bmi_interaction     2392 non-null   float64
dtypes: float64(30)
memory usage: 560.8 KB